version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

    networks:
      - prod

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    networks:
      - prod

  user-db:
    image: user-db
    container_name: user-db

    expose:
      - '3306'
    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: UserDb
      MYSQL_USER: AdminUser
      MYSQL_PASSWORD: AdminPassword

    volumes:
      - mysql:/var/lib/mysql

    networks:
      - prod

volumes:
  mysql:

networks:
  prod:
    driver: bridge